# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - cicd-rm97858

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_ddc6e7b65fa84b3fa18583b9b98e4d59 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ca9907011d944a30b17173339995ef45 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ddc6e7b65fa84b3fa18583b9b98e4d59 }}/docker.io/library/my-image-name:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cicd-rm97858'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8a3297e81a5149c98b89840422f37184 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ddc6e7b65fa84b3fa18583b9b98e4d59 }}/docker.io/library/my-image-name:${{ github.sha }}'